# This is a basic workflow to help you get started with Actions
# 抄艾佬的作品https://github.com/HighCWu/onnxruntime

name: DangoOCR2EXE

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # 此处将涉及编译后whl适用的平台
    runs-on: windows-2019
    
    strategy:
      matrix:
        python-version: ['3.8']
    name: 当Python环境为 ${{ matrix.python-version }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

#       - name: Install VS 2019
#         run: |
#           choco install visualstudio2019community
#           choco install visualstudio2019-workload-nativedesktop
          
#       - name: Get specific version CMake, v3.18.4
#         run: choco install cmake --version=3.18.4

      # Build Ort DML Wheel for Python
      - name: 正在编译 ${{ matrix.python-version }} 的Whl文件
        run: |
          # 填写需要编译Whl包的Git仓库，此处以QPT为例
          chcp 65001
          git clone https://github.com/PantsuDango/DangoOCR
          cd DangoOCR/server
          python -m pip install -U setuptools wheel qpt
          python -m pip install -r requirements_with_opt.txt
          $env:QPT_Action="True"
          echo "from qpt.executor import CreateExecutableModule\n\nmodule = CreateExecutableModule(work_dir="./",\n\nlauncher_py_path="./run.py",\nsave_path="./../out")\nmodule.make()" > tmp.py
          python tmp.py
        
      - name: 上传文件
        uses: actions/upload-artifact@v2
        with: 
          name: EXE-${{ matrix.python-version }}
          path: DangoOCR/out
