# This is a basic workflow to help you get started with Actions
# 抄艾佬的作品https://github.com/HighCWu/onnxruntime

name: 使用QPT生成EXE

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      git_url:
        description: '源码Git地址 | [Git Url] | Example https://github.com/QPT-Family/QPT[QPT为Repo名]'
        required: true
        default: 'https://github.com/QPT-Family/QPT'
      work_dir:
        description: '源码工作目录 | [仓库名] + [工作目录位置] | Example QPT/unit_test/sandbox_paddleocr'
        required: true
        default: 'QPT/unit_test/sandbox_paddleocr'
      out_dir:
        description: '输出目录 | [仓库名]] + [Action输出位置] | Example QPT/unit_test/out'
        required: true
        default: 'QPT/unit_test/out'
      requirements:
        description: '工作目录下的依赖文件 | Example requirements_with_opt.txt'
        required: true
        default: 'requirements_with_opt.txt'
      qpt2exe:
        description: '工作目录下QPT打包脚本 | Example qpt2exe.py'
        required: true
        default: 'qpt2exe.py'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # 此处将涉及编译后whl适用的平台
    runs-on: windows-2019
    
    strategy:
      matrix:
        python-version: ['3.8']
    name: 环境情况-Python ${{ matrix.python-version }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

#       - name: Install VS 2019
#         run: |
#           choco install visualstudio2019community
#           choco install visualstudio2019-workload-nativedesktop
          
#       - name: Get specific version CMake, v3.18.4
#         run: choco install cmake --version=3.18.4

      # Build Ort DML Wheel for Python
      - name: 正在编译 ${{ matrix.python-version }} 的EXE文件
        run: |
          # 填写需要编译Whl包的Git仓库，此处以QPT为例
          chcp 65001
          git clone ${{ github.event.inputs.git_url }}
          cd ${{ github.event.inputs.work_dir }}
          python -m pip install -U setuptools wheel qpt
          python -m pip install -r ${{ github.event.inputs.requirements }}
          $env:PYTHONIOENCODING="utf-8"
          $env:QPT_Action="True"
          python ${{ github.event.inputs.qpt2exe }}
          Compress-Archive -Path ${{ github.event.inputs.out_dir }} -DestinationPath ${{ github.event.inputs.out_dir }}\comb\comb.zip
        
      - name: 上传文件
        uses: actions/upload-artifact@v2
        with: 
          name: EXE-${{ matrix.python-version }}
          path: ${{ github.event.inputs.out_dir }}\comb
